#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        fs-tools-config
#------------------------------------------------------
# lee la configuración de fs-tools
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
# fecha:	lun abr 20 07:22:23 CEST 2020
#######################################################

declare -r DIR_CONFIG="/etc/fs-tools
