#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        fs-tools
#------------------------------------------------------
# Ejecuta una variedad de comandos para la información
#   y manipulación del sistema de ficheros
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
# fecha:	vie abr 17 14:41:56 CEST 2020
#######################################################

# directorios instalación
declare -r LIB_DIR="tools/functions"
declare -r CONF_DIR="datos/etc/fs-tools"

# color
declare -r msg_panic="\e[0;101;30m"
declare -r msg_error="\e[0;40;31m"
declare -r msg_warning="\e[0;40;33m"
declare -r msg_ok="\e[0;40;32m"
declare -r msg_end="\e[0m"
declare -r msg_emphasis="\e[1;37m"

declare -r currentdate=$(date)

if [[ $# -gt 0 && $1 == "-v" ]]; then verbose=0; shift; fi
if [ $# -lt 1 ]; then
    echo -e $msg_panic" Faltan parámetros "$msg_end
    exit 255
fi

util="$1"
shift

if [ ! -r "$LIB_DIR/$util.sh" ]; then
    echo -e $msg_error"Error: el comando $msg_panic'$util'$msg_error no existe"$msg_end
    echo -e $msg_emphasis"utilice 'fs-tools lscommands' para un listado de comandos"$msg_end
    exit 254
fi

# carga la función solicitada
source "$LIB_DIR/$util.sh"

if [ "$verbose" ]; then
    echo -en "\n$msg_emphasis"
    printf '\055%.0s' {1..70}
    printf '\n%-40s%30s\n' "$(basename $0) $util ${*}" "$currentdate"
    printf '\055%.0s' {1..70}; echo ""
    $util -v $@
    retcode=$?
    printf '\055%.0s' {1..70}; echo ""
    echo -e $msg_end
    exit $retcode
else
    $util $@
    exit $?
fi
